//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriveTest
    {
        public decimal prospect_id { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal salesman_id { get; set; }
        public decimal id { get; set; }
        public decimal test_car_id { get; set; }
        public string details { get; set; }
    
        public virtual Prospect Prospect { get; set; }
        public virtual Salesman Salesman { get; set; }
        public virtual TestCar TestCar { get; set; }
    }
}
