//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public decimal order_id { get; set; }
        public System.DateTime date { get; set; }
        public string series { get; set; }
        public decimal number { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
